[[pages]]
path = "/"
screenshotTimestamp = "2026-05-14T13:08:06Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/8258f2b7-973b-4ece-8fb3-b8acc36e7713/42d383e6-f7bc-4bed-83c3-d89cecfcaca2/0zgmpR2"

[[pages]]
path = "/login"
screenshotTimestamp = "2026-05-09T04:31:56Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/8258f2b7-973b-4ece-8fb3-b8acc36e7713/42d383e6-f7bc-4bed-83c3-d89cecfcaca2/i7oe9yf"

[[pages]]
path = "/students"
screenshotTimestamp = "2026-05-14T12:49:49Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/8258f2b7-973b-4ece-8fb3-b8acc36e7713/42d383e6-f7bc-4bed-83c3-d89cecfcaca2/Qhr3Rar"

[[pages]]
path = "/report"
screenshotTimestamp = "2026-05-14T12:58:15Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/8258f2b7-973b-4ece-8fb3-b8acc36e7713/42d383e6-f7bc-4bed-83c3-d89cecfcaca2/VCrCHyj"
